# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 10:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=11)),
                ('code', models.CharField(max_length=6)),
                ('update_time', models.DateTimeField(default=datetime.datetime(2016, 11, 22, 10, 14, 32, 285456))),
            ],
        ),
    ]
